version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    restart: no
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/config:/etc/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_PLUGINS=rabbitmq_management
    networks:
      - my-network

  rocketmq_namesrv:
    image: rocketmqinc/rocketmq:latest
    container_name: rocketmq_namesrv
    command: sh mqnamesrv
    ports:
      - "9876:9876"
    volumes:
      - ./rocketmq/logs/namesrv:/rocketmq/namesrv/logs
    networks:
      - my-network

  rocketmq_broker:
    image: rocketmqinc/rocketmq:latest
    container_name: rocketmq_broker
    command: sh mqbroker -n rocketmq_namesrv:9876
    ports:
      - "10909:10909"
      - "10911:10911"
    environment:
      - NAME_ADDR=rocketmq_namesrv:9876
    volumes:
      - ./rocketmq/logs/broker:/rocketmq/logs
      - ./rocketmq/store:/rocketmq/store
    depends_on:
      - rocketmq_namesrv
    networks:
      - my-network

  rocketmq_console:
    image: styletang/rocketmq-console-ng:latest
    container_name: rocketmq_console
    restart: no
    ports:
      - "8090:8080"
    environment:
      - JAVA_OPTS=-Drocketmq.config.namesrvAddr=rocketmq_namesrv:9876
    depends_on:
      - rocketmq_namesrv
    networks:
      - my-network

networks:
  my-network:
    driver: bridge